title: Tho Le
description: My personal website
author: Tho Le
github: https://github.com/tom-tin
about: Ph.D. candidate in EECS at Northwestern. Looking for a job in data science.
disqus_shortname: stackproblems
google_analytics: UA-XXXXXXXX-Y
avatar_url: /static/img/face.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      #link: "#"  #putting "#" points back to "http://127.0.0.1:4000/#"
      link: "https://www.facebook.com/thongocle"
    - icon: fa-twitter
      link: "https://twitter.com/thokata"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/tho-le-66002859/"
    - icon: fa-stack-exchange
      link: "#"
    - icon: fa-github
      link: "https://github.com/tom-tin"

share:
  twitter_username: tom-tin
  fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: My publications
      url: /publications/
    - text: My Projects
      url: /projects/
    - text: XML Feed
      url: /feed.xml


url: "https://thonle.github.io/"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
